"""
FinStack Signal Outcome Tracker
--------------------------------
Logs every BUY/HOLD/SELL signal generated by finstack tools,
then tracks actual stock performance 7 and 30 days later.

This builds the data moat: over time, you can prove which agents
are most accurate and on which sectors/market-cap segments.

Storage: local SQLite (~/.finstack/signals.db)
         OR Supabase if SUPABASE_URL + SUPABASE_SERVICE_KEY are set

Schema:
  signals(id, symbol, signal, source, price_at_signal, score,
          agent_votes, created_at, checked_7d, return_7d,
          checked_30d, return_30d, outcome_7d, outcome_30d)

Outcome labels:
  "correct"   — signal direction matched actual move
  "wrong"     — signal direction opposite to actual move
  "neutral"   — HOLD and stock was within ±2% — neither right nor wrong
"""

import json
import logging
import sqlite3
from datetime import datetime, timezone, timedelta
from pathlib import Path

logger = logging.getLogger("finstack.signal_tracker")

DB_PATH = Path.home() / ".finstack" / "signals.db"


# ─── DB setup ────────────────────────────────────────────────────────────────

def _get_conn() -> sqlite3.Connection:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    _ensure_schema(conn)
    return conn


def _ensure_schema(conn: sqlite3.Connection):
    conn.execute("""
        CREATE TABLE IF NOT EXISTS signals (
            id            TEXT PRIMARY KEY,
            symbol        TEXT NOT NULL,
            signal        TEXT NOT NULL,          -- BUY / HOLD / SELL
            source        TEXT NOT NULL,          -- 'brief' | 'debate' | 'score' | 'manual'
            price_at_signal REAL,
            score         REAL,
            agent_votes   TEXT,                   -- JSON: {"BUY": 4, "HOLD": 1, "SELL": 1}
            created_at    TEXT NOT NULL,
            check_7d_at   TEXT,                   -- when to check (created_at + 7d)
            check_30d_at  TEXT,
            checked_7d    INTEGER DEFAULT 0,      -- 0=pending, 1=done
            checked_30d   INTEGER DEFAULT 0,
            price_7d      REAL,
            price_30d     REAL,
            return_7d     REAL,                   -- % return
            return_30d    REAL,
            outcome_7d    TEXT,                   -- 'correct' | 'wrong' | 'neutral'
            outcome_30d   TEXT
        )
    """)
    conn.commit()


# ─── Core: log a signal ──────────────────────────────────────────────────────

def log_signal(
    symbol: str,
    signal: str,
    source: str = "brief",
    price: float | None = None,
    score: float | None = None,
    agent_votes: dict | None = None,
) -> str:
    """
    Log a signal to the local tracker DB.
    Returns the signal ID.

    Args:
        symbol:      NSE symbol (e.g. RELIANCE)
        signal:      BUY / HOLD / SELL
        source:      where the signal came from
        price:       price at signal time (fetched automatically if None)
        score:       confidence score (avg of agent scores, -1 to +1)
        agent_votes: dict of vote counts {"BUY": n, "HOLD": n, "SELL": n}
    """
    symbol = symbol.upper().replace(".NS", "").replace(".BO", "")
    signal = signal.upper()

    # Fetch current price if not provided
    if price is None:
        price = _fetch_price(symbol)

    now = datetime.now(tz=timezone.utc)
    sig_id = f"{symbol}_{source}_{int(now.timestamp())}"

    check_7d  = (now + timedelta(days=7)).isoformat()
    check_30d = (now + timedelta(days=30)).isoformat()

    try:
        conn = _get_conn()
        conn.execute(
            """INSERT OR IGNORE INTO signals
               (id, symbol, signal, source, price_at_signal, score, agent_votes,
                created_at, check_7d_at, check_30d_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                sig_id, symbol, signal, source,
                price, score,
                json.dumps(agent_votes) if agent_votes else None,
                now.isoformat(), check_7d, check_30d,
            ),
        )
        conn.commit()
        conn.close()
        logger.info("Signal logged: %s %s @ ₹%s [%s]", symbol, signal, price, sig_id)
    except Exception as e:
        logger.error("Failed to log signal: %s", e)

    return sig_id


# ─── Check outcomes for pending signals ──────────────────────────────────────

def check_pending_outcomes() -> dict:
    """
    Check all signals whose 7d/30d window has elapsed.
    Fetches current price, computes return, labels outcome.
    Returns summary of what was checked.
    """
    now = datetime.now(tz=timezone.utc).isoformat()
    updated = {"7d": 0, "30d": 0, "errors": 0}

    try:
        conn = _get_conn()
        # 7-day pending
        rows_7d = conn.execute(
            "SELECT * FROM signals WHERE checked_7d=0 AND check_7d_at <= ?", (now,)
        ).fetchall()

        for row in rows_7d:
            price_now = _fetch_price(row["symbol"])
            if price_now and row["price_at_signal"]:
                ret = round((price_now - row["price_at_signal"]) / row["price_at_signal"] * 100, 2)
                outcome = _label_outcome(row["signal"], ret)
                conn.execute(
                    "UPDATE signals SET checked_7d=1, price_7d=?, return_7d=?, outcome_7d=? WHERE id=?",
                    (price_now, ret, outcome, row["id"]),
                )
                updated["7d"] += 1
            else:
                updated["errors"] += 1

        # 30-day pending
        rows_30d = conn.execute(
            "SELECT * FROM signals WHERE checked_30d=0 AND check_30d_at <= ?", (now,)
        ).fetchall()

        for row in rows_30d:
            price_now = _fetch_price(row["symbol"])
            if price_now and row["price_at_signal"]:
                ret = round((price_now - row["price_at_signal"]) / row["price_at_signal"] * 100, 2)
                outcome = _label_outcome(row["signal"], ret)
                conn.execute(
                    "UPDATE signals SET checked_30d=1, price_30d=?, return_30d=?, outcome_30d=? WHERE id=?",
                    (price_now, ret, outcome, row["id"]),
                )
                updated["30d"] += 1
            else:
                updated["errors"] += 1

        conn.commit()
        conn.close()
    except Exception as e:
        logger.error("Outcome check error: %s", e)
        updated["errors"] += 1

    return updated


def _label_outcome(signal: str, return_pct: float) -> str:
    """Label whether the signal was correct, wrong, or neutral."""
    if signal == "BUY":
        if return_pct >= 2:
            return "correct"
        elif return_pct <= -2:
            return "wrong"
        return "neutral"
    elif signal == "SELL":
        if return_pct <= -2:
            return "correct"
        elif return_pct >= 2:
            return "wrong"
        return "neutral"
    else:  # HOLD
        if abs(return_pct) <= 3:
            return "correct"
        return "neutral"


# ─── Accuracy stats ───────────────────────────────────────────────────────────

def get_accuracy_stats(
    source: str | None = None,
    symbol: str | None = None,
    days: int = 30,
) -> dict:
    """
    Compute accuracy statistics from tracked signals.

    Args:
        source: filter by signal source (e.g. 'brief', 'debate')
        symbol: filter by specific stock
        days:   look back N days (default 30)

    Returns:
        Dict with accuracy %, avg return, signal breakdown, top symbols.
    """
    try:
        conn = _get_conn()
        cutoff = (datetime.now(tz=timezone.utc) - timedelta(days=days)).isoformat()

        filters = ["created_at >= ?"]
        params: list = [cutoff]

        if source:
            filters.append("source = ?")
            params.append(source)
        if symbol:
            filters.append("symbol = ?")
            params.append(symbol.upper())

        where = " AND ".join(filters)

        # 7-day outcomes
        rows = conn.execute(
            f"SELECT * FROM signals WHERE {where} AND checked_7d=1", params
        ).fetchall()

        conn.close()
    except Exception as e:
        return {"error": str(e)}

    if not rows:
        return {
            "signals_tracked": 0,
            "accuracy_7d": None,
            "avg_return_7d": None,
            "message": "No completed signals yet. Signal outcomes take 7 days to resolve.",
        }

    total = len(rows)
    correct = sum(1 for r in rows if r["outcome_7d"] == "correct")
    wrong   = sum(1 for r in rows if r["outcome_7d"] == "wrong")
    neutral = sum(1 for r in rows if r["outcome_7d"] == "neutral")
    returns = [r["return_7d"] for r in rows if r["return_7d"] is not None]

    # Per signal type
    buy_rows  = [r for r in rows if r["signal"] == "BUY"]
    sell_rows = [r for r in rows if r["signal"] == "SELL"]
    hold_rows = [r for r in rows if r["signal"] == "HOLD"]

    def _acc(lst):
        if not lst:
            return None
        return round(sum(1 for r in lst if r["outcome_7d"] == "correct") / len(lst) * 100, 1)

    # Top performing symbols
    sym_returns: dict[str, list[float]] = {}
    for r in rows:
        if r["return_7d"] is not None:
            sym_returns.setdefault(r["symbol"], []).append(r["return_7d"])

    top_symbols = sorted(
        [{"symbol": s, "avg_return_7d": round(sum(v) / len(v), 2), "signals": len(v)}
         for s, v in sym_returns.items()],
        key=lambda x: x["avg_return_7d"], reverse=True
    )[:5]

    return {
        "signals_tracked": total,
        "period_days": days,
        "accuracy_7d": {
            "overall_pct": round(correct / total * 100, 1) if total else None,
            "correct": correct,
            "wrong": wrong,
            "neutral": neutral,
        },
        "avg_return_7d": round(sum(returns) / len(returns), 2) if returns else None,
        "by_signal_type": {
            "BUY":  {"count": len(buy_rows),  "accuracy_pct": _acc(buy_rows)},
            "HOLD": {"count": len(hold_rows), "accuracy_pct": _acc(hold_rows)},
            "SELL": {"count": len(sell_rows), "accuracy_pct": _acc(sell_rows)},
        },
        "top_symbols_by_return": top_symbols,
        "source_filter": source,
    }


def get_signal_history(symbol: str | None = None, limit: int = 20) -> list[dict]:
    """Get recent signals with their outcomes."""
    try:
        conn = _get_conn()
        if symbol:
            rows = conn.execute(
                "SELECT * FROM signals WHERE symbol=? ORDER BY created_at DESC LIMIT ?",
                (symbol.upper(), limit),
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM signals ORDER BY created_at DESC LIMIT ?", (limit,)
            ).fetchall()
        conn.close()
    except Exception as e:
        return [{"error": str(e)}]

    return [
        {
            "id": r["id"],
            "symbol": r["symbol"],
            "signal": r["signal"],
            "source": r["source"],
            "price_at_signal": r["price_at_signal"],
            "score": r["score"],
            "created_at": r["created_at"],
            "outcome_7d": r["outcome_7d"],
            "return_7d": r["return_7d"],
            "outcome_30d": r["outcome_30d"],
            "return_30d": r["return_30d"],
        }
        for r in rows
    ]


# ─── Helper: fetch live price ─────────────────────────────────────────────────

def _fetch_price(symbol: str) -> float | None:
    try:
        import yfinance as yf
        ticker = yf.Ticker(f"{symbol}.NS")
        fast = ticker.fast_info
        price = getattr(fast, "last_price", None)
        if price:
            return round(float(price), 2)
        # Fallback: last close from history
        hist = ticker.history(period="2d")
        if not hist.empty:
            return round(float(hist["Close"].iloc[-1]), 2)
    except Exception as e:
        logger.debug("Price fetch failed for %s: %s", symbol, e)
    return None
